<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>OBDReader.TestRunner</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Core\**\*.cs" LinkBase="Core" />
  </ItemGroup>

</Project>
